from pathlib import Path
import sys
import re

import sqlglot
from sqlglot import exp
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import PydanticToolsParser, JsonOutputParser
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage

from src.config import config
from src.models import AgentState, SQLBuilderOutput, SQLRevisorOutput
from src.prompts import SYSTEM_PROMPT_SQL_BUILDER, SYSTEM_PROMPT_SQL_REVISOR, USER_PROMPT_TEMPLATE_SQL_BUILDER, USER_PROMPT_TEMPLATE_SQL_REVISOR
from src.schema_loader import schema_context

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import logging
logging.basicConfig(
    level=logging.INFO, # Set the lowest severity level to capture
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler("app.log"),   # Save logs to a file
        logging.StreamHandler()          # Print logs to the console
    ]
)
logger = logging.getLogger(__name__)

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0,
)

def sql_builder(state: AgentState) -> AgentState:
    """ This node will build initial SQL query from theuser requirement. """
    logger.info("start sql_builder")
    structured_llm = llm.with_structured_output(SQLBuilderOutput)

    prompt = ChatPromptTemplate.from_messages([
        ("system", SYSTEM_PROMPT_SQL_BUILDER),
        ("user", USER_PROMPT_TEMPLATE_SQL_BUILDER),
    ]).format_messages(
        allowed_schemas = ", ".join(config.allowed_schemas),
        blocked_tables = ", ".join(config.blocked_tables),
        blocked_columns = ", ".join(config.blocked_columns),
        schema_context = schema_context,
        requirement = state["requirement"],
        max_rows = config.max_rows
    )

    result = structured_llm.invoke(prompt)
    
    state.update({
        "sql": result["sql"],
        "explanation": result["explanation"],
        "tables_used": result["tables_used"],
        "assumptions": result["assumptions"],
    })
    logger.info("="*50)
    logger.info(state)
    logger.info("end sql_builder")
    return state

WRITE_KEYWORDS_RE = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|MERGE|GRANT|REVOKE|COPY|CALL|DO|VACUUM|ANALYZE)\b",
    re.IGNORECASE,
)
COMMENT_RE = re.compile(r"(--|/\*)")
LIMIT_RE = re.compile(r"\bLIMIT\s+(?P<limit>\d+)\b", re.IGNORECASE)

def sql_validator(state: AgentState) -> AgentState:
    """ This node will validate SQL query generated by sql_builder. """
    logger.info("start sql_validator")

    sql = state["sql"]
    errors: list[str] = []
    warnings: list[str] = []
    cleaned_sql = sql.strip().rstrip(";").strip()

    if not cleaned_sql:
        state.update({
            "is_valid": False,
            "errors": ["SQL is empty."]
        })
        return state
    
    if COMMENT_RE.search(cleaned_sql):
        errors.append("SQL comments are not allowed.")
    if WRITE_KEYWORDS_RE.search(cleaned_sql):
        errors.append("Only read-only SELECT queries are allowed.")

    try:
        parsed_statements = sqlglot.parse(cleaned_sql, read="postgres")
    except sqlglot.errors.ParseError as exc:
        state.update({
            "is_valid": False,
            "errors": [f"SQL parse error: {exc}"]
        })
        return state
    
    if len(parsed_statements) != 1:
        errors.append("Only one SQL statement is allowed.")
    
    expression = parsed_statements[0]
    if not isinstance(expression, (exp.Select, exp.Union, exp.With)):
        errors.append("The statement must be a SELECT query.")

    if not LIMIT_RE.search(sql):
        warnings.append("No LIMIT found")
    
    ### We can extent the logic to validate if sql is using only specified table / columns and blocked table / cpolumns are not used.
    state.update({
        "is_valid": len(errors) <= 0,
        "errors": errors,
        "warnings": warnings
    })
    logger.info("="*50)
    logger.info(state)
    logger.info("end sql_validator")
    return state

def sql_revisor(state: AgentState) -> AgentState:
    """ This node will validate SQL query generated by sql_builder. """
    logger.info("start sql_revisor")
    structured_llm = llm.with_structured_output(SQLRevisorOutput)

    prompt = ChatPromptTemplate.from_messages([
        ("system", SYSTEM_PROMPT_SQL_REVISOR),
        ("user", USER_PROMPT_TEMPLATE_SQL_REVISOR)
    ]).format_messages(
        allowed_schemas = ", ".join(config.allowed_schemas),
        blocked_tables = ", ".join(config.blocked_tables),
        blocked_columns = ", ".join(config.blocked_columns),
        schema_context = schema_context,
        requirement = state["requirement"],
        max_rows = config.max_rows,
        sql = state["sql"],
        errors = state["errors"],
        warnings = state["warnings"]
    )

    result = structured_llm.invoke(prompt)
    logger.info("="*50)
    logger.info(result)
    state.update({
        "revised_sql": result["revised_sql"],
        "explanation": result["explanation"],
        "tables_used": result["tables_used"],
        "assumptions": result["assumptions"],
        "attempt": state["attempt"] + 1
    })
    logger.info("="*50)
    logger.info(state)

    logger.info("end sql_revisor")
    return state